# Spring Boot configuration
server:
  port: 8091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 123456
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml