server:
  port: 7095

spring:
  # Generate Events Publisher or Subsriber
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      properties:
        request.timeout.ms: ${KAFKA_REQUEST_TIMEOUT:5000}
  cloud:
    stream:
      bindings:
        smsVerificationCreatedSubscribe:
          destination: sms-verification-created
        smsVerificationDeliveredpublish:
          destination: sms-verification-delivered
      binders:
        binderName:
          type: kafka

logging:
  level:
    ru.diasoft: ${LOGGING_LEVEL:DEBUG}

