spring:
  kafka:
    bootstrap-servers: localhost:9092
  cloud:
    stream:
      binders:
        binderName:
          type: kafka
      bindings:
        #Подписка на широковещательное сообщение (сообщение получают все подписчики)
        broadcasts:
          destination: demo

